// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	dynamodb2 "brain2-backend/infrastructure/dynamodb"
	"brain2-backend/internal/config"
	"brain2-backend/internal/handlers"
	"brain2-backend/internal/repository"
	"brain2-backend/internal/service/category"
	"brain2-backend/internal/service/memory"
	"brain2-backend/pkg/api"
	"context"
	config2 "github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/eventbridge"
	"github.com/awslabs/aws-lambda-go-api-proxy/chi"
	"github.com/go-chi/chi/v5"
	"github.com/google/wire"
	"net/http"
)

// Injectors from wire.go:

func InitializeAPI() (*chi.Mux, error) {
	client, err := ProvideDynamoDBClient()
	if err != nil {
		return nil, err
	}
	configConfig := config.LoadConfig()
	repository := ProvideRepository(client, configConfig)
	service := ProvideMemoryService(repository)
	eventbridgeClient, err := ProvideEventBridgeClient()
	if err != nil {
		return nil, err
	}
	memoryHandler := ProvideMemoryHandler(service, eventbridgeClient)
	categoryService := ProvideCategoryService(repository)
	categoryHandler := ProvideCategoryHandler(categoryService)
	mux := ProvideRouter(memoryHandler, categoryHandler)
	return mux, nil
}

// wire.go:

// ProvideDynamoDBClient provides a DynamoDB client.
func ProvideDynamoDBClient() (*dynamodb.Client, error) {
	cfg, err := config2.LoadDefaultConfig(context.TODO())
	if err != nil {
		return nil, err
	}
	return dynamodb.NewFromConfig(cfg), nil
}

// ProvideRepository provides the DynamoDB repository implementation.
func ProvideRepository(client *dynamodb.Client, cfg config.Config) repository.Repository {
	return dynamodb2.NewRepository(client, cfg.TableName, cfg.IndexName)
}

// ProvideMemoryService provides the memory service.
func ProvideMemoryService(repo repository.Repository) memory.Service {
	return memory.NewService(repo)
}

// ProvideCategoryService provides the category service.
func ProvideCategoryService(repo repository.Repository) category.Service {
	return category.NewService(repo)
}

// ProvideEventBridgeClient provides an EventBridge client.
func ProvideEventBridgeClient() (*eventbridge.Client, error) {
	cfg, err := config2.LoadDefaultConfig(context.TODO())
	if err != nil {
		return nil, err
	}
	return eventbridge.NewFromConfig(cfg), nil
}

// ProvideMemoryHandler provides the memory handler.
func ProvideMemoryHandler(svc memory.Service, eventBridgeClient *eventbridge.Client) *handlers.MemoryHandler {
	return handlers.NewMemoryHandler(svc, eventBridgeClient)
}

// ProvideCategoryHandler provides the category handler.
func ProvideCategoryHandler(svc category.Service) *handlers.CategoryHandler {
	return handlers.NewCategoryHandler(svc)
}

// ProvideRouter provides the HTTP router with all handlers.
func ProvideRouter(memoryHandler *handlers.MemoryHandler, categoryHandler *handlers.CategoryHandler) *chi.Mux {
	r := chi.NewRouter()

	r.Group(func(r chi.Router) {
		r.Get("/health", func(w http.ResponseWriter, r *http.Request) {
			api.Success(w, http.StatusOK, map[string]string{"status": "ok"})
		})
	})

	r.Group(func(r chi.Router) {
		r.Use(handlers.Authenticator)

		r.Post("/api/nodes", memoryHandler.CreateNode)
		r.Get("/api/nodes", memoryHandler.ListNodes)
		r.Get("/api/nodes/{nodeId}", memoryHandler.GetNode)
		r.Put("/api/nodes/{nodeId}", memoryHandler.UpdateNode)
		r.Delete("/api/nodes/{nodeId}", memoryHandler.DeleteNode)
		r.Post("/api/nodes/bulk-delete", memoryHandler.BulkDeleteNodes)
		r.Get("/api/graph-data", memoryHandler.GetGraphData)

		r.Post("/api/categories", categoryHandler.CreateCategory)
		r.Get("/api/categories", categoryHandler.ListCategories)
		r.Get("/api/categories/{categoryId}", categoryHandler.GetCategory)
		r.Put("/api/categories/{categoryId}", categoryHandler.UpdateCategory)
		r.Delete("/api/categories/{categoryId}", categoryHandler.DeleteCategory)
		r.Post("/api/categories/{categoryId}/nodes", categoryHandler.AssignNodeToCategory)
		r.Get("/api/categories/{categoryId}/nodes", categoryHandler.GetNodesInCategory)
		r.Delete("/api/categories/{categoryId}/nodes/{nodeId}", categoryHandler.RemoveNodeFromCategory)

		r.Get("/api/nodes/{nodeId}/categories", categoryHandler.GetNodeCategories)
		r.Post("/api/nodes/{nodeId}/categories", categoryHandler.CategorizeNode)
	})

	return r
}

// ProvideChiLambda provides the ChiLambdaV2 adapter.
func ProvideChiLambda(router *chi.Mux) *chiadapter.ChiLambdaV2 {
	return chiadapter.NewV2(router)
}

var (
	DynamoDBSet = wire.NewSet(
		ProvideDynamoDBClient, config.LoadConfig, ProvideRepository,
	)

	ServiceSet = wire.NewSet(
		ProvideMemoryService,
		ProvideCategoryService,
	)

	HandlerSet = wire.NewSet(
		ProvideMemoryHandler,
		ProvideCategoryHandler,
		ProvideEventBridgeClient,
	)
)
