// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

// Injectors from wire.go:

// InitializeApplicationContainer wires together the clean container architecture.
// This function uses the CleanSuperSet to create an ApplicationContainer with
// all the focused sub-containers properly initialized and wired.
//
// Wire Process:
//  1. Analyzes all provider functions in CleanSuperSet
//  2. Builds dependency graph ensuring proper initialization order
//  3. Generates wire_gen.go with concrete implementation
//  4. Catches circular dependencies and missing providers at compile time
//
// The generated code is equivalent to manually calling all provider functions
// in the correct order, but without the maintenance burden.
func InitializeApplicationContainer() (*ApplicationContainer, error) {
	config, err := provideConfig()
	if err != nil {
		return nil, err
	}
	applicationContainer, err := provideApplicationContainer(config)
	if err != nil {
		return nil, err
	}
	return applicationContainer, nil
}
