# Base Configuration for Brain2 Backend
# This file contains the default configuration that applies to all environments.
# Environment-specific files (development.yaml, staging.yaml, production.yaml) override these values.

# Configuration version for schema compatibility checking
version: "2.0.0"

# Server configuration
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  shutdown_timeout: 10s
  max_request_size: 10485760  # 10MB
  request_timeout: 30s
  enable_https: false

# Database configuration (DynamoDB)
database:
  table_name: "brain2"
  index_name: "KeywordIndex"
  region: "us-east-1"
  max_retries: 3
  retry_base_delay: 100ms
  connection_pool: 10
  timeout: 10s
  read_capacity: 5
  write_capacity: 5
  enable_backups: false
  enable_streams: false

# AWS configuration
aws:
  region: "us-east-1"
  # Leave empty to use IAM roles or instance profiles
  # access_key_id: ""
  # secret_access_key: ""

# Domain business logic configuration
domain:
  similarity_threshold: 0.3      # Minimum similarity for auto-connections
  max_connections_per_node: 10   # Maximum edges per node
  max_content_length: 20000      # Maximum characters per node (~4 pages)
  document_threshold: 800        # Characters before suggesting document mode
  document_auto_open: 1200       # Characters before auto-opening document editor
  min_keyword_length: 3          # Minimum keyword length for extraction
  recency_weight: 0.2            # Weight for recent nodes in connections
  diversity_threshold: 0.5       # Threshold for connection diversity
  max_tags_per_node: 10          # Maximum tags per node
  max_nodes_per_user: 10000      # Maximum nodes per user

# Infrastructure configuration
infrastructure:
  retry:
    max_retries: 3
    initial_delay: 100ms
    max_delay: 5s
    backoff_factor: 2.0
    jitter_factor: 0.1
    retry_on_timeout: true
    retry_on_5xx: true
  
  circuit_breaker:
    failure_threshold: 0.5      # Trip after 50% failures
    success_threshold: 0.8      # Reset after 80% success
    minimum_requests: 10        # Minimum requests before evaluation
    window_size: 10s           # Time window for evaluation
    open_duration: 30s         # How long to stay open
    half_open_requests: 3      # Requests to test in half-open state
  
  # Idempotency TTL Configuration
  # Controls how long idempotency records are retained in DynamoDB
  # These records prevent duplicate processing of identical requests
  # After expiration, the same request will be treated as new
  # 
  # Valid formats: "1h", "24h", "7d", "168h"
  # Range: 1h (minimum) to 168h/7d (maximum)
  # 
  # To override via environment variable: IDEMPOTENCY_TTL=48h
  # 
  # Considerations when setting TTL:
  # - Shorter TTL (1-6h): Good for high-volume APIs where duplicate requests are unlikely after a few hours
  # - Medium TTL (24h): Default, balances storage costs with duplicate prevention
  # - Longer TTL (2-7d): Good for critical operations where duplicates must be prevented for days
  idempotency_ttl: 24h
  health_check_interval: 30s
  graceful_shutdown_delay: 5s

# Caching configuration
cache:
  provider: "memory"           # Options: memory, redis, memcached
  max_items: 1000
  ttl: 5m
  query_ttl: 1m
  redis:
    host: "localhost"
    port: 6379
    db: 0
    pool_size: 10

# Metrics configuration
metrics:
  provider: "prometheus"       # Options: prometheus, datadog, cloudwatch, statsd
  interval: 10s
  namespace: "brain2"
  prometheus:
    port: 9090
    path: "/metrics"

# Logging configuration
logging:
  level: "info"               # Options: debug, info, warn, error, fatal
  format: "json"              # Options: json, console
  output: "stdout"            # Options: stdout, stderr, file
  max_size: 100               # MB (when output is file)
  max_age: 30                 # days
  max_backups: 10
  compress: true

# Security configuration
security:
  jwt_secret: "${JWT_SECRET:-change-this-secret-in-production}"
  jwt_expiry: 24h
  api_key_header: "X-API-Key"
  enable_auth: true
  allowed_origins:
    - "*"
  secure_headers: true
  enable_csrf: false
  csrf_token_length: 32

# Rate limiting configuration
rate_limit:
  enabled: false
  requests_per_minute: 100
  burst: 10
  cleanup_interval: 1m
  by_ip: true
  by_user: false
  by_api_key: false

# CORS configuration
cors:
  enabled: true
  allowed_origins:
    - "*"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "*"
  exposed_headers: []
  allow_credentials: false
  max_age: 86400

# Distributed tracing configuration
tracing:
  enabled: false
  provider: "jaeger"          # Options: jaeger, zipkin, xray, datadog
  service_name: "brain2-backend"
  sample_rate: 0.1           # Sample 10% of requests
  agent_host: "localhost"
  agent_port: 6831

# Event bus configuration
events:
  provider: "eventbridge"     # Options: eventbridge, kafka, rabbitmq, sns
  event_bus_name: "default"
  topic_prefix: "brain2"
  retry_attempts: 3
  batch_size: 10

# Feature flags for gradual rollout
features:
  # Core features
  enable_caching: false
  enable_auto_connect: true
  enable_ai_processing: false
  enable_metrics: false
  enable_tracing: false
  enable_event_bus: false
  
  # Infrastructure features
  enable_retries: true
  enable_circuit_breaker: false
  enable_rate_limiting: false
  enable_compression: false
  
  # Debugging features
  enable_debug_endpoints: false
  enable_profiling: false
  enable_logging: true
  verbose_logging: false
  
  # Experimental features
  enable_graphql: false
  enable_websockets: false
  enable_batch_api: false