# Development Environment Configuration
# This file overrides base.yaml for the development environment.
# It provides developer-friendly settings with verbose logging and debugging features.

environment: "development"

# Server configuration for development
server:
  port: 8080
  enable_https: false

# Database configuration for development
database:
  table_name: "brain2-dev"
  # Lower capacity for development
  read_capacity: 1
  write_capacity: 1

# AWS configuration for development
aws:
  # Uncomment to use LocalStack for local development
  # endpoint: "http://localhost:4566"

# Domain configuration for development
domain:
  # More lenient settings for testing
  max_connections_per_node: 20
  max_content_length: 50000

# Logging configuration for development
logging:
  level: "debug"              # Verbose logging
  format: "console"           # Human-readable format
  output: "stdout"

# Security configuration for development
security:
  jwt_secret: "development-secret-do-not-use-in-production"
  enable_auth: false          # Disable auth for easier testing
  secure_headers: false       # Less strict for local development
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:5173"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:5173"

# CORS configuration for development
cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:5173"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:5173"
  allow_credentials: true

# Feature flags for development
features:
  # Enable all debugging features
  enable_debug_endpoints: true
  enable_profiling: true
  verbose_logging: true
  
  # Enable features for testing
  enable_caching: true
  enable_metrics: true
  enable_tracing: true
  
  # Experimental features for development
  enable_graphql: true
  enable_websockets: true
  enable_batch_api: true

# Cache configuration for development
cache:
  provider: "memory"
  max_items: 100              # Smaller cache for development
  ttl: 1m                     # Shorter TTL for testing

# Metrics configuration for development
metrics:
  prometheus:
    port: 9090
    path: "/metrics"

# Tracing configuration for development
tracing:
  enabled: true
  sample_rate: 1.0           # Sample all requests in development