// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"backend2/application/commands/bus"
	"backend2/application/ports"
	bus2 "backend2/application/queries/bus"
	"backend2/infrastructure/config"
	"context"
	"github.com/google/wire"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// InitializeContainer creates a fully wired container
func InitializeContainer(ctx context.Context, cfg *config.Config) (*Container, error) {
	logger, err := ProvideLogger(cfg)
	if err != nil {
		return nil, err
	}
	awsConfig, err := ProvideAWSConfig(ctx, cfg)
	if err != nil {
		return nil, err
	}
	client := ProvideDynamoDBClient(awsConfig)
	nodeRepository := ProvideNodeRepository(client, cfg, logger)
	edgeRepository := ProvideEdgeRepository(client, cfg, logger)
	graphRepository := ProvideGraphRepository(client, nodeRepository, edgeRepository, cfg, logger)
	eventbridgeClient := ProvideEventBridgeClient(awsConfig)
	eventBus := ProvideEventBus(eventbridgeClient, cfg, logger)
	commandBus := ProvideCommandBus(nodeRepository, edgeRepository, graphRepository, eventBus, logger)
	cache := ProvideInMemoryCache()
	queryBus := ProvideQueryBus(graphRepository, nodeRepository, edgeRepository, cache, logger)
	container := &Container{
		Config:     cfg,
		Logger:     logger,
		NodeRepo:   nodeRepository,
		GraphRepo:  graphRepository,
		EdgeRepo:   edgeRepository,
		EventBus:   eventBus,
		CommandBus: commandBus,
		QueryBus:   queryBus,
		Cache:      cache,
	}
	return container, nil
}

// wire.go:

// Container holds all application dependencies
type Container struct {
	Config     *config.Config
	Logger     *zap.Logger
	NodeRepo   ports.NodeRepository
	GraphRepo  ports.GraphRepository
	EdgeRepo   ports.EdgeRepository
	EventBus   ports.EventBus
	CommandBus *bus.CommandBus
	QueryBus   *bus2.QueryBus
	Cache      ports.Cache
}

// SuperSet is the main provider set containing all providers
var SuperSet = wire.NewSet(
	ProvideLogger,
	ProvideAWSConfig,
	ProvideDynamoDBClient,
	ProvideEventBridgeClient,
	ProvideNodeRepository,
	ProvideGraphRepository,
	ProvideEdgeRepository,
	ProvideEventBus,
	ProvideCommandBus,
	ProvideQueryBus,
	ProvideInMemoryCache, wire.Struct(new(Container), "*"),
)
